#
# Module manifest for module 'NewManifest'
#
# Generated by: Chris Lewis
#
# Generated on: 12/1/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ZertoModule.psm1'

# Version number of this module.
ModuleVersion = '0.8.4'

# ID used to uniquely identify this module
GUID = 'a7c23e30-0879-42f4-9e1c-bffbe723b02b'

# Author of this module
Author = 'Chris Lewis'

# Company or vendor of this module
CompanyName = 'Nuveen'

# Copyright statement for this module
Copyright = '(c) 2016 Chris Lewis. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Zerto REST API Powershell Wrapping module'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Add-ZertoVPG', 'Add-ZertoVRA', 'Commit-ZertoVPGSetting', 
               'Convert-ZertoVPGToVPGSetting', 'Get-ZertoAlert', 
               'Get-ZertoAlertEntities', 'Get-ZertoAlertHelpIdentifierDescription', 
               'Get-ZertoAlertHelpIdentifiers', 'Get-ZertoAlertLevels', 
               'Get-ZertoAlerts', 'Get-ZertoAuthToken', 'Get-ZertoEvent', 
               'Get-ZertoEventCategories', 'Get-ZertoEventEntities', 
               'Get-ZertoEvents', 'Get-ZertoEventTypes', 'Get-ZertoLocalSite', 
               'Get-ZertoLocalSiteID', 'Get-ZertoLocalSitePairingStatuses', 
               'Get-ZertoPeerSite', 'Get-ZertoPeerSiteID', 'Get-ZertoPeerSites', 
               'Get-ZertoResoureReport', 'Get-ZertoResoureReportAdvFilter', 
               'Get-ZertoRESTAPIs', 'Get-ZertoServiceProfile', 
               'Get-ZertoServiceProfileID', 'Get-ZertoServiceProfiles', 
               'Get-ZertoSite', 'Get-ZertoSiteDatastoreClusterID', 
               'Get-ZertoSiteDatastoreClusters', 'Get-ZertoSiteDatastoreID', 
               'Get-ZertoSiteDatastores', 'Get-ZertoSiteFolderID', 
               'Get-ZertoSiteFolders', 'Get-ZertoSiteHost', 
               'Get-ZertoSiteHostClusterID', 'Get-ZertoSiteHostClusters', 
               'Get-ZertoSiteHostID', 'Get-ZertoSiteHosts', 'Get-ZertoSiteID', 
               'Get-ZertoSiteNetworkID', 'Get-ZertoSiteNetworks', 
               'Get-ZertoSiteOrgVCDs', 'Get-ZertoSiteResourcePools', 
               'Get-ZertoSites', 'Get-ZertoSiteVApps', 'Get-ZertoSiteVcdVapps', 
               'Get-ZertoSiteVMID', 'Get-ZertoSiteVMs', 'Get-ZertoTask', 
               'Get-ZertoTasks', 'Get-ZertoTasksTypes', 
               'Get-ZertoVirtualizationSite', 'Get-ZertoVirtualizationSiteID', 
               'Get-ZertoVirtualizationSites', 'Get-ZertoVM', 'Get-ZertoVMID', 
               'Get-ZertoVMs', 'Get-ZertoVPG', 'Get-ZertoVPGCheckpointID', 
               'Get-ZertoVPGCheckpointLastID', 'Get-ZertoVPGCheckpoints', 
               'Get-ZertoVPGCheckpointSummary', 'Get-ZertoVPGEntityTypes', 
               'Get-ZertoVPGFailoverCommitPolicies', 
               'Get-ZertoVPGFailoverShutdownPolicies', 'Get-ZertoVPGID', 
               'Get-ZertoVPGPriorities', 'Get-ZertoVPGRetentionPolicies', 
               'Get-ZertoVPGs', 'Get-ZertoVPGSetting', 'Get-ZertoVPGSettingBackup', 
               'Get-ZertoVPGSettingBackupDayOfWeek', 
               'Get-ZertoVPGSettingBackupRetentionPeriod', 
               'Get-ZertoVPGSettingBackupSchedulerPeriod', 
               'Get-ZertoVPGSettingBasic', 'Get-ZertoVPGSettingBootGroup', 
               'Get-ZertoVPGSettingID', 'Get-ZertoVPGSettingJournal', 
               'Get-ZertoVPGSettingNetworks', 'Get-ZertoVPGSettingPriority', 
               'Get-ZertoVPGSettingRecovery', 'Get-ZertoVPGSettings', 
               'Get-ZertoVPGSettingScripting', 'Get-ZertoVPGSettingVM', 
               'Get-ZertoVPGSettingVMNIC', 'Get-ZertoVPGSettingVMNICs', 
               'Get-ZertoVPGSettingVMs', 'Get-ZertoVPGSettingVMVolume', 
               'Get-ZertoVPGSettingVMVolumes', 'Get-ZertoVPGStatuses', 
               'Get-ZertoVPGSubstatuses', 'Get-ZertoVRA', 'Get-ZertoVRAID', 
               'Get-ZertoVRAIPConfigurationTypes', 'Get-ZertoVRAs', 
               'Get-ZertoVRAStatuses', 'Get-ZertoZOrg', 'Get-ZertoZOrgs', 
               'Invoke-ZertoAlertDismiss', 'Invoke-ZertoAlertUndismiss', 
               'Invoke-ZertoVPGFailoverCommit', 'Invoke-ZertoVPGFailoverRollback', 
               'Invoke-ZertoVPGForceSync', 'Invoke-ZertoVPGPause', 
               'Invoke-ZertoVPGResume', 'Invoke-ZertoVRAUpgrade', 
               'New-ZertoFailoverIPAddress', 'New-ZertoVPGSettingBasic', 
               'New-ZertoVPGSettingBootgroup', 'New-ZertoVPGSettingJournal', 
               'New-ZertoVPGSettingJournalLimitation', 
               'New-ZertoVPGVirtualMachine', 'New-ZertoVRAIPAddressConfig', 
               'Remove-ZertoAuthToken', 'Remove-ZertoVPG', 'Remove-ZertoVPGSetting', 
               'Remove-ZertoVRA', 'Set-ZertoAuthToken', 'Set-ZertoVPGSettingBasic', 
               'Start-ZertoVPGClone', 'Start-ZertoVPGFailover', 
               'Start-ZertoVPGFailoverTest', 'Stop-ZertoVPGClone', 
               'Stop-ZertoVPGFailoverTest'

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 
               'C:\Scripts\Zerto\ZertoModule\ZertoModule\ZertoModule.psm1-help.xml'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/ChristopherGLewis/ZertoModule/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ChristopherGLewis/ZertoModule'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/ChristopherGLewis/ZertoModule/blob/master/README.md'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

